trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

variables:
  - name: ConvertNetCore
    value: true

resources:
  repositories:
    - repository: niveristand-custom-device-build-tools
      type: github
      ref: main
      endpoint: nivs-custom-devices
      name: ni/niveristand-custom-device-build-tools
  pipelines:
    - pipeline: InstrumentAddonClasses
      source:   ni.niveristand-instrument-addon-classes
      trigger:  
        branches: 
          include:
            - main

stages:

# =====================================================================
# LINUX BUILD
# =====================================================================
- template: azure-templates/linux-stage.yml@niveristand-custom-device-build-tools
  parameters:
    stageName: LinuxBuild

    lvVersionsToBuild:
      - version: '2027'
        bitness: '64bit'

    buildSteps:
      - id: 'instrument-addon-custom-device_configuration_release'
        projectLocation: 'Source/Addon/Instrument Addon.lvproj'
        buildOperation: 'ExecuteBuildSpec'
        target: 'My Computer'
        buildSpec: 'Configuration(Linux) Release'
      
    releaseVersion: '26.8.0'
    branch: 'main'
    debugBuild: 'no'
    buildOutputLocation: 'Built'
    archiveLocation: '\\nirvana\Measurements\VeriStandAddons\instrument_addon_custom_device'
    repoName: 'niveristand-instrument-addon-custom-device'
